photoswipe_dynamic_caption.settings:
  type: config_object
  label: Settings
  mapping:
    options:
      type: mapping
      label: Caption options
      mapping:
        type:
          type: string
          label: 'Type'
        mobileLayoutBreakpoint:
          type: integer
          label: 'Maximum window width at which mobile layout should be used'
        horizontalEdgeThreshold:
          type: integer
          label: 'Horizontal edge threshold'
        mobileCaptionOverlapRatio:
          type: float
          label: 'Mobile caption overlap ratio'
        verticallyCenterImage:
          type: boolean
          label: 'Vertically center image'

field.formatter.third_party.photoswipe_dynamic_caption:
  type: mapping
  label: 'Photoswipe field formatter caption options'
  mapping:
    photoswipe_caption:
      type: string
      label: 'Photoswipe Caption'
    photoswipe_caption_custom:
      type: string
      label: 'Photoswipe Caption Custom'
