name: lando-egs
recipe: drupal9
config:
  webroot: .
  php: "8.1"
services:
  adminer:
    type: compose
    services:
      image: dehy/adminer
      command: "/bin/s6-svscan /etc/services.d"
    portforward: true
proxy:
  adminer:
    - adminer.lando-egs.lndo.site
